In [67]:
import tensorflow as tf
import pandas as pd
import numpy as np
import yfinance as yf

In [68]:
goo = yf.download("GOOGL", start="2005-01-01")
goo.head()

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2004-12-31,99.714714,100.040039,96.376373,96.491493,96.491493,15321663
2005-01-03,98.798798,101.921921,97.827827,101.456459,101.456459,31656712
2005-01-04,100.800804,101.566566,96.836838,97.347343,97.347343,27484288
2005-01-05,96.821823,98.548546,96.211212,96.851852,96.851852,16456727
2005-01-06,97.637634,98.048050,93.953957,94.369370,94.369370,20753426

In [69]:
ms = yf.download("MSFT", start="2005-01-01")
ms.head()

[*********************100%***********************]  1 of 1 completed

                 Open       High        Low      Close  Adj Close     Volume
Date
2004-12-31  26.750000  26.900000  26.680000  26.719999  18.939941   54959500
2005-01-03  26.799999  26.950001  26.650000  26.740000  18.954119   65002900
2005-01-04  26.870001  27.100000  26.660000  26.840000  19.025003  109442100
2005-01-05  26.840000  27.100000  26.760000  26.780001  18.982475   72463500
2005-01-06  26.850000  27.059999  26.639999  26.750000  18.961206   76890500

In [70]:
ap = yf.download("AAPL", start="2005-01-01")
ap.head()

[*********************100%***********************]  1 of 1 completed

                Open      High       Low     Close  Adj Close      Volume
Date
2004-12-31  1.158750  1.160714  1.143393  1.150000   0.983270   278588800
2005-01-03  1.156786  1.162679  1.117857  1.130179   0.966323   691992000
2005-01-04  1.139107  1.169107  1.124464  1.141786   0.976248  1096810400
2005-01-05  1.151071  1.165179  1.143750  1.151786   0.984798   680433600
2005-01-06  1.154821  1.159107  1.130893  1.152679   0.985561   705555200

In [71]:
goo_ar = goo['Close']
print(goo_ar)

Date
2004-12-31      96.491493
2005-01-03     101.456459
2005-01-04      97.347343
2005-01-05      96.851852
2005-01-06      94.369370
                 ...
2022-05-23    2229.760010
2022-05-24    2119.399902
2022-05-25    2116.100098
2022-05-26    2155.850098
2022-05-27    2246.330078
Name: Close, Length: 4383, dtype: float64

In [72]:
ms_ar = ms['Close']
print(ms_ar)

Date
2004-12-31     26.719999
2005-01-03     26.740000
2005-01-04     26.840000
2005-01-05     26.780001
2005-01-06     26.750000
                 ...
2022-05-23    260.649994
2022-05-24    259.619995
2022-05-25    262.519989
2022-05-26    265.899994
2022-05-27    273.239990
Name: Close, Length: 4383, dtype: float64

In [73]:
ap_ar = ap['Close']
print(ap_ar)

Date
2004-12-31      1.150000
2005-01-03      1.130179
2005-01-04      1.141786
2005-01-05      1.151786
2005-01-06      1.152679
                 ...
2022-05-23    143.110001
2022-05-24    140.360001
2022-05-25    140.520004
2022-05-26    143.779999
2022-05-27    149.639999
Name: Close, Length: 4383, dtype: float64

In [77]:
x_data = []
for i in range(4383):
    x_data.append([goo_ar[i-1], ms_ar[i-1]])

y_data = []
for i in range(4383):
    y_data.append([ap_ar[i-1]])

In [ ]:
from tensorflow import keras
from tensorflow.keras import layers

In [ ]:
model = keras.Sequential()
model.add(layers.Embedding(input_dim=1000, output_dim=64))

# The output of GRU will be a 3D tensor of shape (batch_size, timesteps, 256)
model.add(layers.GRU(256, return_sequences=True, dropout=True))

# The output of SimpleRNN will be a 2D tensor of shape (batch_size, 128)
model.add(layers.SimpleRNN(128))

model.add(layers.Dense(10))

model.summary()

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 embedding_8 (Embedding)     (None, None, 64)          64000

 gru_7 (GRU)                 (None, None, 256)         247296

 simple_rnn_5 (SimpleRNN)    (None, 128)               49280

 dense_8 (Dense)             (None, 10)                1290

=================================================================
Total params: 361,866
Trainable params: 361,866
Non-trainable params: 0
_________________________________________________________________

In [83]:
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer="sgd",
    metrics=["accuracy"],
)


model.fit(np.array(x_data), np.array(y_data), batch_size=2)

ValueError: in user code:

    File "/home/jhyunwoo/anaconda3/envs/tf29/lib/python3.9/site-packages/keras/engine/training.py", line 1051, in train_function  *
        return step_function(self, iterator)
    File "/home/jhyunwoo/anaconda3/envs/tf29/lib/python3.9/site-packages/keras/engine/training.py", line 1040, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/jhyunwoo/anaconda3/envs/tf29/lib/python3.9/site-packages/keras/engine/training.py", line 1030, in run_step  **
        outputs = model.train_step(data)
    File "/home/jhyunwoo/anaconda3/envs/tf29/lib/python3.9/site-packages/keras/engine/training.py", line 889, in train_step
        y_pred = self(x, training=True)
    File "/home/jhyunwoo/anaconda3/envs/tf29/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None

    ValueError: Exception encountered when calling layer "gru_7" (type GRU).

    `rate` must be a scalar tensor or a float in the range [0, 1). Received: rate=1.0

    Call arguments received by layer "gru_7" (type GRU):
      • inputs=tf.Tensor(shape=(None, 2, 64), dtype=float32)
      • mask=None
      • training=True
      • initial_state=None